baseURL = "https://vc24902.github.io/aws-worklog/"
languageCode = "en-us"
title = "AWS Worklog"
theme = "ananke"

canonifyURLs = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

disableKinds = ["RSS"]

[outputs]
home = ["HTML"]

[params]
mainSections = ["posts"]
customCSS = ["css/style.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]

[languages.en]
languageName = "English"
languageCode = "en-US"
weight = 1

[languages.vi]
languageName = "Tiếng Việt"
languageCode = "vi-VN"
weight = 2