baseURL = "https://vc24902.github.io/aws-worklog/"
languageCode = "en-us"
title = "AWS Worklog"
theme = "ananke"

canonifyURLs = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
home = ["HTML"]

disableKinds = ["RSS"]

[params]
mainSections = ["posts"]
customCSS = ["css/style.css"]

# Cho phép HTML trong Markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

############################
# Languages
############################

[languages]

[languages.en]
languageName = "English"
languageCode = "en-US"
weight = 1

[languages.vi]
languageName = "Tiếng Việt"
languageCode = "vi-VN"
weight = 2