baseURL = "https://vc24902.github.io/aws-worklog/"
languageCode = "en-us"
title = "AWS Worklog"
theme = "ananke"

canonifyURLs = true

[outputs]
home = ["HTML"]

disableKinds = ["RSS"]   # 🔥 QUAN TRỌNG

[params]
mainSections = ["posts"]
[params]
  customCSS = ["css/style.css"]